# SPDX-FileCopyrightText: Copyright (c) The helly25 authors (helly25.com)
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Exposes the composable extras to Starlark, derived from MODULE.bazel.

`load("@xff_extras//:extras.bzl", "EXTRAS_TARGETS")` gives the `@module//...` pattern of every extra,
so a BUILD rule that must name them all (today: //:refresh_compile_commands) needs no hand-kept list
that can silently fall behind.

MODULE.bazel is the single source of truth: every extra is a `bazel_dep` plus a `local_path_override`
pointing under `extra_modules/`. Starlark cannot read MODULE.bazel from a BUILD file, hence this
repository rule, which reads it at fetch time and writes the list out as a `.bzl`. tools/extras.py
performs the same derivation for the shell (CI's test command); the parsing rule is simple enough that
two readers of one file beat two hand-kept lists, and extras_test.py pins the shapes both accept.
"""

# The directory that holds the removable extras. `xff_extras_api` is also a local module but is NOT an
# extra: it is the always-built shared seam, deliberately at the top level so that a minimal source
# archive can drop extra_modules/ wholesale.
_EXTRAS_DIR = "extra_modules/"

def _extra_modules(module_bazel):
    """Returns the module name of every local_path_override whose path is under extra_modules/."""
    modules = []
    for block in module_bazel.split("local_path_override(")[1:]:
        block = block.split(")")[0]
        name = None
        under_extras = False
        for field in block.split(","):
            if "module_name" in field and "\"" in field:
                name = field.split("\"")[1]
            elif "path" in field and "\"" in field:
                under_extras = field.split("\"")[1].startswith(_EXTRAS_DIR)
        if name and under_extras:
            modules.append(name)
    return sorted(modules)

def _xff_extras_impl(repository_ctx):
    module_bazel = repository_ctx.read(Label("@@//:MODULE.bazel"))
    modules = _extra_modules(module_bazel)
    if not modules:
        fail("no extras found in MODULE.bazel: the local_path_override parse must have broken")
    targets = ["\"@{}//...\"".format(module) for module in modules]
    repository_ctx.file("WORKSPACE", "")
    repository_ctx.file("BUILD.bazel", "")
    repository_ctx.file(
        "extras.bzl",
        """# Generated by //tools:extras_repo.bzl from MODULE.bazel. Do not edit.
EXTRAS_MODULES = [{modules}]
EXTRAS_TARGETS = [{targets}]
""".format(
            modules = ", ".join(["\"{}\"".format(module) for module in modules]),
            targets = ", ".join(targets),
        ),
    )

_xff_extras = repository_rule(
    implementation = _xff_extras_impl,
    doc = "Generates @xff_extras//:extras.bzl listing the extras declared in MODULE.bazel.",
    # Re-run whenever the source of truth changes, so the generated list cannot go stale.
    attrs = {"_module_bazel": attr.label(default = Label("@@//:MODULE.bazel"), allow_single_file = True)},
)

def _extras_extension_impl(_module_ctx):
    _xff_extras(name = "xff_extras")

extras_extension = module_extension(
    implementation = _extras_extension_impl,
    doc = "Makes @xff_extras available; see the module docstring.",
)
