"""Build rule for embedding a Brotli-compressed language vocabulary."""

load("@rules_cc//cc:defs.bzl", "cc_library")

def language_database(name, src, uncompressed_size):
    generated_cc = name + "_generated.cc"
    generated_h = name + "_generated.h"
    native.genrule(
        name = name + "_gen",
        srcs = [src],
        outs = [generated_cc, generated_h],
        cmd = """(
          echo '// Generated by language_database(). Do not edit.'
          echo '#ifndef XFF_LANGUAGE_DB_DATA_GENERATED_H_'
          echo '#define XFF_LANGUAGE_DB_DATA_GENERATED_H_'
          echo '#include <cstddef>'
          echo '#include <cstdint>'
          echo '#include <span>'
          echo 'namespace xff::language_db::data {'
          echo 'std::span<const std::uint8_t> Compressed();'
          echo 'std::size_t UncompressedSize();'
          echo '}  // namespace xff::language_db::data'
          echo '#endif  // XFF_LANGUAGE_DB_DATA_GENERATED_H_'
        ) > $(location """ + generated_h + """)
        (
          echo '// Generated by language_database(). Do not edit.'
          printf '#include "%s"\n' '""" + generated_h + """'
          echo '#include <array>'
          echo 'namespace xff::language_db::data { namespace {'
          echo 'constexpr std::array<std::uint8_t, '$$(wc -c < $(location """ + src + """))'> kCompressed = {'
          od -An -v -tu1 $(location """ + src + """) | awk '{ for (i = 1; i <= NF; ++i) printf "%s,", $$i; print "" }'
          echo '};'
          echo '}  // namespace'
          echo 'std::span<const std::uint8_t> Compressed() { return kCompressed; }'
          printf 'std::size_t UncompressedSize() { return %s; }\n' '""" + str(uncompressed_size) + """'
          echo '}  // namespace xff::language_db::data'
        ) > $(location """ + generated_cc + """)
        """,
    )
    cc_library(
        name = name,
        srcs = [generated_cc],
        hdrs = [generated_h],
    )
