# SPDX-FileCopyrightText: Copyright (c) M. Boerger, the MBO Works authors
# SPDX-License-Identifier: Apache-2.0

"""Build rule for embedding and registering an authoritative license body."""

load("@rules_cc//cc:defs.bzl", "cc_library")

def license_body(name, spdx, src):
    """Embeds an authoritative license file and registers it by SPDX id."""
    generated = name + "_generated.cc"
    native.genrule(
        name = name + "_gen",
        srcs = [src],
        outs = [generated],
        cmd = """(
          echo '// Generated by license_body(). Do not edit.'
          echo '#include "xff/license/notice.h"'
          echo 'namespace xff::license { namespace {'
          printf 'const LicenseBodyRegistrar kBody{{.spdx = "%s", .text = R"xff_license(' '""" + spdx + """'
          cat $(location """ + src + """)
          printf ')xff_license"}};\n'
          echo '}  // namespace'
          echo '}  // namespace xff::license'
        ) > $@""",
    )
    cc_library(
        name = name,
        srcs = [generated],
        deps = ["@xff_extras_api//:license_notice_cc"],
        alwayslink = True,
    )
