"""Build rule for embedding a removable MIME vocabulary JSON layer."""

load("@rules_cc//cc:defs.bzl", "cc_library")

def mime_database(name, database_name, src):
    generated = name + "_generated.cc"
    native.genrule(
        name = name + "_gen",
        srcs = [src],
        outs = [generated],
        cmd = """(
          echo '// Generated by mime_database(). Do not edit.'
          echo '#include <string>'
          echo '#include "xff/matching/mime/database.h"'
          echo 'namespace xff::mime { namespace {'
          echo 'const std::string kJson = [] {'
          echo '  std::string result;'
          LC_ALL=C awk '{ for (i = 1; i <= length($$0); i += 60000) printf "  result.append(R\\\"xff_mime(%s)xff_mime\\\");\\n", substr($$0, i, 60000) }' $(location """ + src + """)
          echo '  return result;'
          echo '}();'
          printf 'const DatabaseRegistrar kDatabase{{.name = "%s", .json = kJson}};\n' '""" + database_name + """'
          echo '}  // namespace'
          echo '}  // namespace xff::mime'
        ) > $@""",
    )
    cc_library(
        name = name,
        srcs = [generated],
        deps = ["@xff_extras_api//:mime_database_cc"],
        alwayslink = True,
    )
